os: osx

env:
  global:
    - TMUX=y
    - TMUX_PLUGIN_MANAGER_PATH="/Users/travis/.tmux/plugins/"
    - GIT_AUTHOR_NAME="Michael Mior"
    - GIT_AUTHOR_EMAIL=michael.mior@gmail.com

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi

install: ./macos-setup.sh
script:
  - sed -i 's/overwrite_all=false/overwrite_all=true/g' script/install
  - sed -i 's/readlink/greadlink/g' script/install
  - ./script/install
